Add ecr support

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -15,6 +15,7 @@ TAGONLY=""
 ENABLE_ROLLBACK=false
 AWS_CLI=$(which aws)
 AWS_ECS="$AWS_CLI --output json ecs"
+AWS_ECR="$AWS_CLI --output json ecr"
 
 function usage() {
     cat <<EOM
@@ -225,6 +226,14 @@ function parseImageName() {
       imageWithoutTag="$useImage"
       if [[ ! -z ${tag+undefined-guard} ]]; then
         useImage="$useImage:$tag"
+      fi
+
+      if [[ "$imageWithoutTag" =~ 'dkr.ecr' ]]; then
+        ECR_IMAGE=`$AWS_ECR describe-images --repository-name=$img | jq -r ".imageDetails[] | select(.imageTags[] == \"$tag\")"`
+        if [[ -z $ECR_IMAGE ]]; then
+          echo "ERROR: image not found in ECR. image = $useImage"
+          exit 1
+        fi
       fi
 
     else
